/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.Constructor;
import java.nio.file.Paths;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Marton
 */
public class NewGame extends javax.swing.JPanel {

    /**
     * Creates new form NewGame
     */        
    private final MainWindow window;    
    private Constructor constructor;
    private static String playerName;

    public NewGame(final MainWindow window) {
        this.window = window;
        initComponents();
        constructor1Label.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/RB.png"));
        constructor2Label.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/FR.png"));
        constructor3Label.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/MC.png"));
        window.setSaved(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        pickConstructor3Button = new javax.swing.JButton();
        pickConstructor1Button = new javax.swing.JButton();
        pickConstructor2Button = new javax.swing.JButton();
        constructor1Label = new javax.swing.JLabel();
        constructor2Label = new javax.swing.JLabel();
        constructor3Label = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Welcome to Formula One");

        pickConstructor3Button.setText("Choose");
        pickConstructor3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickConstructor3ButtonActionPerformed(evt);
            }
        });

        pickConstructor1Button.setText("Choose");
        pickConstructor1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickConstructor1ButtonActionPerformed(evt);
            }
        });

        pickConstructor2Button.setText("Choose");
        pickConstructor2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickConstructor2ButtonActionPerformed(evt);
            }
        });

        constructor1Label.setText("jLabel2");
        constructor1Label.setToolTipText("Difficulity: EASY");
        constructor1Label.setMaximumSize(new java.awt.Dimension(100, 200));
        constructor1Label.setMinimumSize(new java.awt.Dimension(100, 200));
        constructor1Label.setPreferredSize(new java.awt.Dimension(100, 200));

        constructor2Label.setText("jLabel3");
        constructor2Label.setToolTipText("Difficulity: NORMAL");
        constructor2Label.setMaximumSize(new java.awt.Dimension(100, 200));
        constructor2Label.setMinimumSize(new java.awt.Dimension(100, 200));
        constructor2Label.setPreferredSize(new java.awt.Dimension(100, 200));

        constructor3Label.setText("jLabel4");
        constructor3Label.setToolTipText("Difficulity: HARD");
        constructor3Label.setMaximumSize(new java.awt.Dimension(100, 200));
        constructor3Label.setMinimumSize(new java.awt.Dimension(100, 200));
        constructor3Label.setPreferredSize(new java.awt.Dimension(100, 200));

        infoLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        infoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLabel.setText("Choose from the following constructors");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(pickConstructor1Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 391, Short.MAX_VALUE)
                        .addComponent(pickConstructor2Button)
                        .addGap(333, 333, 333))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(constructor1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(258, 258, 258)
                        .addComponent(constructor2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(constructor3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pickConstructor3Button)
                        .addGap(130, 130, 130))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(constructor1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(constructor2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(constructor3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pickConstructor1Button)
                    .addComponent(pickConstructor2Button)
                    .addComponent(pickConstructor3Button))
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pickConstructor1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickConstructor1ButtonActionPerformed
        constructor = Constructor.REDBULL;
        window.setConstructor(constructor);
        String name = JOptionPane.showInputDialog("Player's name: ", "Player");
        if(name != null)
        {
            if(name.trim().length() == 0)
            {
                name = "Player";
            }
            if(name.length() > 45)
            {
                name = name.substring(0, 44);
            }
            playerName = name.replace(" ", "_");
            window.getGameModel().setMoney(90000);
            window.setPlayerName(playerName);
            window.switchToGameField(this);
            window.getGameModel().getTimeSimulation().start();
        }
    }//GEN-LAST:event_pickConstructor1ButtonActionPerformed

    private void pickConstructor2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickConstructor2ButtonActionPerformed
        constructor = Constructor.FERRARI;
        window.setConstructor(constructor);
        String name = JOptionPane.showInputDialog("Player's name: ", "Player");
        if(name != null)
        {
            if(name.trim().length() == 0)
            {
                name = "Player";
            }
            if(name.length() > 45)
            {
                name = name.substring(0, 44);
            }
            playerName = name.replace(" ", "_");
            window.getGameModel().setMoney(80000);
            window.setPlayerName(playerName);
            window.switchToGameField(this);
            window.getGameModel().getTimeSimulation().start();
        }
    }//GEN-LAST:event_pickConstructor2ButtonActionPerformed

    private void pickConstructor3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickConstructor3ButtonActionPerformed
        constructor = Constructor.MERCEDES;
        window.setConstructor(constructor);
        String name = JOptionPane.showInputDialog("Player's name: ", "Player");
        if(name != null)
        {
            if(name.trim().length() == 0)
            {
                name = "Player";
            }
            if(name.length() > 45)
            {
                name = name.substring(0, 44);
            }
            playerName = name.replace(" ", "_");
            window.getGameModel().setMoney(70000);
            window.setPlayerName(playerName);
            window.switchToGameField(this);
            window.getGameModel().getTimeSimulation().start();
        }
    }//GEN-LAST:event_pickConstructor3ButtonActionPerformed

    public static String getPlayerName() {
        return playerName;
    }

    public void setPlayerName(String playerName) {
        this.playerName = playerName;
    }
        
    public Constructor getConstructor() {
        return constructor;
    }
    
    public void setConstructor(Constructor constructor) {
        this.constructor = constructor;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel constructor1Label;
    private javax.swing.JLabel constructor2Label;
    private javax.swing.JLabel constructor3Label;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JButton pickConstructor1Button;
    private javax.swing.JButton pickConstructor2Button;
    private javax.swing.JButton pickConstructor3Button;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
