/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Source.DepartmentState;
import Source.UnitType;
import java.awt.Color;
import java.nio.file.Paths;
import javax.swing.ImageIcon;

/**
 *
 * @author Marton
 */
public class ResourceAndDevelopment extends javax.swing.JPanel {
    private DepartmentState state = null;
    private final MainWindow window;
    /**
     * Creates new form ResourceAndDevelopment
     */
    public ResourceAndDevelopment(final MainWindow window) {
        this.window = window;
        initComponents();
        switchToBuildings();
        buildingsButton.setBackground(Color.GREEN);
        state = DepartmentState.BUILDINGS;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buildingsButton = new javax.swing.JButton();
        tracksButton = new javax.swing.JButton();
        developmentButton = new javax.swing.JButton();
        buildingPic1 = new javax.swing.JLabel();
        buildingPic2 = new javax.swing.JLabel();
        buildingPic3 = new javax.swing.JLabel();
        buildingPic4 = new javax.swing.JLabel();
        buildingPic5 = new javax.swing.JLabel();
        buildingPic6 = new javax.swing.JLabel();
        buildingPic7 = new javax.swing.JLabel();
        buildingPic8 = new javax.swing.JLabel();
        buildingPic9 = new javax.swing.JLabel();
        price1 = new javax.swing.JLabel();
        price2 = new javax.swing.JLabel();
        price3 = new javax.swing.JLabel();
        price4 = new javax.swing.JLabel();
        price5 = new javax.swing.JLabel();
        price6 = new javax.swing.JLabel();
        price9 = new javax.swing.JLabel();
        price8 = new javax.swing.JLabel();
        price7 = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        title3 = new javax.swing.JLabel();
        backToGFButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        buildingsButton.setText("Buildings");
        buildingsButton.setMaximumSize(new java.awt.Dimension(120, 60));
        buildingsButton.setPreferredSize(new java.awt.Dimension(120, 60));
        buildingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildingsButtonActionPerformed(evt);
            }
        });

        tracksButton.setText("Tracks");
        tracksButton.setMaximumSize(new java.awt.Dimension(120, 60));
        tracksButton.setPreferredSize(new java.awt.Dimension(120, 60));
        tracksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tracksButtonActionPerformed(evt);
            }
        });

        developmentButton.setText("Development");
        developmentButton.setMaximumSize(new java.awt.Dimension(120, 60));
        developmentButton.setPreferredSize(new java.awt.Dimension(120, 60));
        developmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                developmentButtonActionPerformed(evt);
            }
        });

        buildingPic1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buildingPic1.setToolTipText("Chasing Department, 1dev, 1work point");
        buildingPic1.setMaximumSize(new java.awt.Dimension(100, 100));
        buildingPic1.setMinimumSize(new java.awt.Dimension(100, 100));
        buildingPic1.setPreferredSize(new java.awt.Dimension(100, 100));
        buildingPic1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buildingPic1MousePressed(evt);
            }
        });

        buildingPic2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buildingPic2.setToolTipText("Downforce Department, 3 dev points");
        buildingPic2.setPreferredSize(new java.awt.Dimension(100, 100));
        buildingPic2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buildingPic2MousePressed(evt);
            }
        });

        buildingPic3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buildingPic3.setToolTipText("Aero Department, 5 dev points");
        buildingPic3.setPreferredSize(new java.awt.Dimension(100, 100));
        buildingPic3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buildingPic3MousePressed(evt);
            }
        });

        buildingPic4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buildingPic4.setToolTipText("Durability Department, 1dev, 1work point");
        buildingPic4.setPreferredSize(new java.awt.Dimension(100, 100));
        buildingPic4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buildingPic4MousePressed(evt);
            }
        });

        buildingPic5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buildingPic5.setToolTipText("Chasing Department, 5 dev points");
        buildingPic5.setPreferredSize(new java.awt.Dimension(100, 100));
        buildingPic5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buildingPic5MousePressed(evt);
            }
        });

        buildingPic6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buildingPic6.setToolTipText("Factory, 3dev, 3work points");
        buildingPic6.setPreferredSize(new java.awt.Dimension(100, 100));
        buildingPic6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buildingPic6MousePressed(evt);
            }
        });

        buildingPic7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buildingPic7.setToolTipText("House, 2 work points");
        buildingPic7.setPreferredSize(new java.awt.Dimension(100, 100));
        buildingPic7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buildingPic7MousePressed(evt);
            }
        });

        buildingPic8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buildingPic8.setToolTipText("Hotel, 5 work points");
        buildingPic8.setPreferredSize(new java.awt.Dimension(100, 100));
        buildingPic8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buildingPic8MousePressed(evt);
            }
        });

        buildingPic9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buildingPic9.setToolTipText("Store, 4 work points");
        buildingPic9.setPreferredSize(new java.awt.Dimension(100, 100));
        buildingPic9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buildingPic9MousePressed(evt);
            }
        });

        price1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        price1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        price1.setText("25000$");
        price1.setToolTipText("");
        price1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        price1.setMaximumSize(new java.awt.Dimension(100, 40));
        price1.setMinimumSize(new java.awt.Dimension(100, 40));
        price1.setPreferredSize(new java.awt.Dimension(100, 40));

        price2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        price2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        price2.setText("20000$");
        price2.setToolTipText("");
        price2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        price2.setMaximumSize(new java.awt.Dimension(100, 40));
        price2.setMinimumSize(new java.awt.Dimension(100, 40));
        price2.setPreferredSize(new java.awt.Dimension(100, 40));

        price3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        price3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        price3.setText("25000$");
        price3.setToolTipText("");
        price3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        price3.setMaximumSize(new java.awt.Dimension(100, 40));
        price3.setMinimumSize(new java.awt.Dimension(100, 40));
        price3.setPreferredSize(new java.awt.Dimension(100, 40));

        price4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        price4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        price4.setText("1000$");
        price4.setToolTipText("");
        price4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        price4.setMaximumSize(new java.awt.Dimension(100, 40));
        price4.setMinimumSize(new java.awt.Dimension(100, 40));
        price4.setPreferredSize(new java.awt.Dimension(100, 40));

        price5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        price5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        price5.setText("1000$");
        price5.setToolTipText("");
        price5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        price5.setMaximumSize(new java.awt.Dimension(100, 40));
        price5.setMinimumSize(new java.awt.Dimension(100, 40));
        price5.setPreferredSize(new java.awt.Dimension(100, 40));

        price6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        price6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        price6.setText("1000$");
        price6.setToolTipText("");
        price6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        price6.setMaximumSize(new java.awt.Dimension(100, 40));
        price6.setMinimumSize(new java.awt.Dimension(100, 40));
        price6.setPreferredSize(new java.awt.Dimension(100, 40));

        price9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        price9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        price9.setText("1000$");
        price9.setToolTipText("");
        price9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        price9.setMaximumSize(new java.awt.Dimension(100, 40));
        price9.setMinimumSize(new java.awt.Dimension(100, 40));
        price9.setPreferredSize(new java.awt.Dimension(100, 40));

        price8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        price8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        price8.setText("1000$");
        price8.setToolTipText("");
        price8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        price8.setMaximumSize(new java.awt.Dimension(100, 40));
        price8.setMinimumSize(new java.awt.Dimension(100, 40));
        price8.setPreferredSize(new java.awt.Dimension(100, 40));

        price7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        price7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        price7.setText("1000$");
        price7.setToolTipText("");
        price7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        price7.setMaximumSize(new java.awt.Dimension(100, 40));
        price7.setMinimumSize(new java.awt.Dimension(100, 40));
        price7.setPreferredSize(new java.awt.Dimension(100, 40));

        title1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        title1.setText("Aero Department");

        title2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        title2.setText("PowerUnit");

        title3.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        title3.setText("Accommodation");

        backToGFButton.setText("Back");
        backToGFButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToGFButtonMouseClicked(evt);
            }
        });
        backToGFButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToGFButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(title1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(price1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(buildingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buildingPic1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buildingPic4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(price7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(price4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buildingPic7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(developmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buildingPic2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buildingPic5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(price2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buildingPic8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(price8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(price5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(price3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buildingPic3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(price6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(price9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buildingPic6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buildingPic9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                                .addComponent(backToGFButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tracksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(236, 236, 236))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buildingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(developmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tracksButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buildingPic2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buildingPic1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buildingPic3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buildingPic4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buildingPic5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buildingPic6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(title3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(backToGFButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(buildingPic8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buildingPic7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buildingPic9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(670, 670, 670))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buildingPic1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buildingPic1MousePressed
        window.getGameModel().getTimeSimulation().NormalTime();
        window.switchToGameField(this);
        if(state == DepartmentState.BUILDINGS)
        {
            window.getGameModel().setNewBuilding(UnitType.CHASINGDEPARTMENT);
        }
        else if(state == DepartmentState.DEVELOPMENT)
        {
            window.getGameModel().setNewBuilding(UnitType.CHASINGDEPARTMENT);
        }
        else if(state == DepartmentState.ACCESSORIES)
        {
            window.getGameModel().setNewBuilding(UnitType.BUSH);
        }
    }//GEN-LAST:event_buildingPic1MousePressed

    private void buildingPic2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buildingPic2MousePressed
        window.getGameModel().getTimeSimulation().NormalTime();
        window.switchToGameField(this);
        if(state == DepartmentState.BUILDINGS)
        {
            window.getGameModel().setNewBuilding(UnitType.DOWNFORCEDEPARTMENT);
        }
        else if(state == DepartmentState.DEVELOPMENT)
        {
            window.getGameModel().setNewBuilding(UnitType.DOWNFORCEDEPARTMENT);
        }
        else if(state == DepartmentState.ACCESSORIES)
        {
            window.getGameModel().setNewBuilding(UnitType.PATH);
        }
    }//GEN-LAST:event_buildingPic2MousePressed

    private void buildingPic3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buildingPic3MousePressed
        window.getGameModel().getTimeSimulation().NormalTime();
        window.switchToGameField(this);
        if(state == DepartmentState.BUILDINGS)
        {
            window.getGameModel().setNewBuilding(UnitType.AERODEPARTMENT);
        }
        else if(state == DepartmentState.DEVELOPMENT)
        {
            window.getGameModel().setNewBuilding(UnitType.AERODEPARTMENT);
        }
        else if(state == DepartmentState.ACCESSORIES)
        {
            window.getGameModel().setNewBuilding(UnitType.TREE);
        }
    }//GEN-LAST:event_buildingPic3MousePressed

    private void buildingPic4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buildingPic4MousePressed
        window.getGameModel().getTimeSimulation().NormalTime();
        window.switchToGameField(this);
        if(state == DepartmentState.BUILDINGS)
        {
            window.getGameModel().setNewBuilding(UnitType.DURABILITYDEPARTMENT);
        }
        else if(state == DepartmentState.DEVELOPMENT)
        {
            window.getGameModel().setNewBuilding(UnitType.DURABILITYDEPARTMENT);
        }
        else if(state == DepartmentState.ACCESSORIES)
        {
            window.getGameModel().setNewBuilding(UnitType.TRACK1);
        }
    }//GEN-LAST:event_buildingPic4MousePressed

    private void buildingPic5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buildingPic5MousePressed
        window.getGameModel().getTimeSimulation().NormalTime();
        window.switchToGameField(this);
        if(state == DepartmentState.BUILDINGS)
        {
            window.getGameModel().setNewBuilding(UnitType.POWERUNITDEPARTMENT);
        }
        else if(state == DepartmentState.DEVELOPMENT)
        {
            window.getGameModel().setNewBuilding(UnitType.POWERUNITDEPARTMENT);
        }
        else if(state == DepartmentState.ACCESSORIES)
        {
            window.getGameModel().setNewBuilding(UnitType.TRACK2);
        }
    }//GEN-LAST:event_buildingPic5MousePressed

    private void buildingPic6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buildingPic6MousePressed
        window.getGameModel().getTimeSimulation().NormalTime();
        window.switchToGameField(this);
        if(state == DepartmentState.BUILDINGS)
        {
            window.getGameModel().setNewBuilding(UnitType.FACTORY);
        }
        else if(state == DepartmentState.DEVELOPMENT)
        {
            window.getGameModel().setNewBuilding(UnitType.FACTORY);
        }
        else if(state == DepartmentState.ACCESSORIES)
        {
            window.getGameModel().setNewBuilding(UnitType.TRACK3);
        }
    }//GEN-LAST:event_buildingPic6MousePressed

    private void buildingPic7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buildingPic7MousePressed
        window.getGameModel().getTimeSimulation().NormalTime();
        window.switchToGameField(this);
        if(state == DepartmentState.BUILDINGS)
        {
            window.getGameModel().setNewBuilding(UnitType.HOUSE);
        }
        else if(state == DepartmentState.DEVELOPMENT)
        {
            window.getGameModel().setNewBuilding(UnitType.HOUSE);
        }
    }//GEN-LAST:event_buildingPic7MousePressed

    private void buildingPic8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buildingPic8MousePressed
        window.getGameModel().getTimeSimulation().NormalTime();
        window.switchToGameField(this);
        if(state == DepartmentState.BUILDINGS)
        {
            window.getGameModel().setNewBuilding(UnitType.HOTEL);
        }
        else if(state == DepartmentState.DEVELOPMENT)
        {
            window.getGameModel().setNewBuilding(UnitType.HOTEL);
        }
    }//GEN-LAST:event_buildingPic8MousePressed

    private void buildingPic9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buildingPic9MousePressed
        window.getGameModel().getTimeSimulation().NormalTime();
        window.switchToGameField(this);
        if(state == DepartmentState.BUILDINGS)
        {
            window.getGameModel().setNewBuilding(UnitType.STORE);
        }
        else if(state == DepartmentState.DEVELOPMENT)
        {
            window.getGameModel().setNewBuilding(UnitType.STORE);
        }
    }//GEN-LAST:event_buildingPic9MousePressed

    private void buildingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildingsButtonActionPerformed
        buildingsButton.setBackground(Color.GREEN);
        tracksButton.setBackground(null);
        developmentButton.setBackground(null);
        state = DepartmentState.BUILDINGS;
        switchToBuildings();
    }//GEN-LAST:event_buildingsButtonActionPerformed

    private void developmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_developmentButtonActionPerformed
        buildingsButton.setBackground(null);
        tracksButton.setBackground(null);
        developmentButton.setBackground(Color.GREEN);
        state = DepartmentState.DEVELOPMENT;
        switchToDevelopment();
    }//GEN-LAST:event_developmentButtonActionPerformed

    private void tracksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tracksButtonActionPerformed
        buildingsButton.setBackground(null);
        tracksButton.setBackground(Color.GREEN);
        developmentButton.setBackground(null);
        state = DepartmentState.ACCESSORIES;
        switchToAccessories();
    }//GEN-LAST:event_tracksButtonActionPerformed

    private void backToGFButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToGFButtonMouseClicked
        window.getGameModel().getTimeSimulation().NormalTime(); 
        window.switchToGameField(this);
    }//GEN-LAST:event_backToGFButtonMouseClicked

    private void backToGFButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToGFButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backToGFButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToGFButton;
    private javax.swing.JLabel buildingPic1;
    private javax.swing.JLabel buildingPic2;
    private javax.swing.JLabel buildingPic3;
    private javax.swing.JLabel buildingPic4;
    private javax.swing.JLabel buildingPic5;
    private javax.swing.JLabel buildingPic6;
    private javax.swing.JLabel buildingPic7;
    private javax.swing.JLabel buildingPic8;
    private javax.swing.JLabel buildingPic9;
    private javax.swing.JButton buildingsButton;
    private javax.swing.JButton developmentButton;
    private javax.swing.JLabel price1;
    private javax.swing.JLabel price2;
    private javax.swing.JLabel price3;
    private javax.swing.JLabel price4;
    private javax.swing.JLabel price5;
    private javax.swing.JLabel price6;
    private javax.swing.JLabel price7;
    private javax.swing.JLabel price8;
    private javax.swing.JLabel price9;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    private javax.swing.JButton tracksButton;
    // End of variables declaration//GEN-END:variables

    private void switchToBuildings() {
        
        buildingPic1.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/Shop/aero_1.png"));
        buildingPic2.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/Shop/aero_2.png"));
        buildingPic3.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/Shop/aero_3.png"));
        buildingPic4.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/Shop/powerunit_1.png"));
        buildingPic5.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/Shop/powerunit_2.jpg"));
        buildingPic6.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/Shop/powerunit_3.png"));
        buildingPic7.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/Shop/house_1.png"));
        buildingPic8.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/Shop/house_2.jpg"));
        buildingPic9.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/Shop/house_3.png"));
        price1.setText("15.000 $");
        price2.setText("15.000 $");
        price3.setText("15.000 $");
        price4.setText("15.000 $");
        price5.setText("15.000 $");
        price6.setText("20.000 $");
        price7.setText("3.000 $");
        price8.setText("4.500 $");
        price9.setText("4.000 $");
        title1.setText("Aero Department");
        title2.setText("Power Unit");
        title3.setText("Accommodation");
        
        buildingPic1.setVisible(true);
        buildingPic2.setVisible(true);
        buildingPic3.setVisible(true);
        buildingPic4.setVisible(true);
        buildingPic5.setVisible(true);
        buildingPic6.setVisible(true);
        buildingPic7.setVisible(true);
        buildingPic8.setVisible(true);
        buildingPic9.setVisible(true);
        
    }

    private void switchToDevelopment() {
        buildingPic1.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/Shop/aero_1.png"));
        buildingPic2.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/Shop/aero_2.png"));
        buildingPic3.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/Shop/aero_3.png"));
        buildingPic4.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/Shop/powerunit_1.png"));
        buildingPic5.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/Shop/powerunit_2.jpg"));
        buildingPic6.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/Shop/powerunit_3.png"));
        price1.setText("15.000 $");
        price2.setText("15.000 $");
        price3.setText("15.000 $");
        price4.setText("15.000 $");
        price5.setText("15.000 $");
        price6.setText("20.000 $");
        price7.setText("");
        price8.setText("");
        price9.setText("");
        title1.setText("Aero Department");
        title2.setText("Power Unit");
        title3.setText("");
        
        buildingPic1.setVisible(true);
        buildingPic2.setVisible(true);
        buildingPic3.setVisible(true);
        buildingPic4.setVisible(true);
        buildingPic5.setVisible(true);
        buildingPic6.setVisible(true);
        buildingPic7.setVisible(false);
        buildingPic8.setVisible(false);
        buildingPic9.setVisible(false);
    }

    private void switchToAccessories() {
        buildingPic1.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/Shop/bush.jpg"));
        buildingPic1.setToolTipText("bush");
        buildingPic2.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/Shop/path.png"));
        buildingPic2.setToolTipText("path");
        buildingPic3.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/Shop//tree.jpg"));
        buildingPic3.setToolTipText("tree");
        buildingPic4.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/Shop/Practice_track_1.png"));
        buildingPic4.setToolTipText("Track-1,3dev,3work");
        buildingPic5.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/Shop/Practice_track_2.gif"));
        buildingPic5.setToolTipText("Track-2,5dev,5work");
        buildingPic6.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/Shop/Practice_track_3.png"));
        buildingPic6.setToolTipText("Track-3,7dev,7work");
        price1.setText("350 $");
        price2.setText("200 $");
        price3.setText("500 $");
        price4.setText("30.000 $");
        price5.setText("50.000 $");
        price6.setText("70.000 $");
        price7.setText("");
        price8.setText("");
        price9.setText("");
        title1.setText("Design elements");
        title2.setText("Tracks");
        title3.setText("");
        buildingPic1.setVisible(true);
        buildingPic2.setVisible(true);
        buildingPic3.setVisible(true);
        buildingPic4.setVisible(true);
        buildingPic5.setVisible(true);
        buildingPic6.setVisible(true);
        buildingPic7.setVisible(false);
        buildingPic8.setVisible(false);
        buildingPic9.setVisible(false);
    }
}
