/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.io.IOException;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Marton
 */
public class Tutorial extends javax.swing.JPanel {

    /**
     * Creates new form Tutorial
     */
    private final MainWindow window;
    private int counter;
    public Tutorial(final MainWindow window) {
        this.window = window;
        counter = 0;
        initComponents();
        picturesLayout.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/tutorial_1.png"));
        pageBackButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backToMenuButton = new javax.swing.JButton();
        titleLayout = new javax.swing.JLabel();
        stepLayout = new javax.swing.JLabel();
        informationLayout = new javax.swing.JLabel();
        picturesLayout = new javax.swing.JLabel();
        pageNextButton = new javax.swing.JButton();
        pageBackButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1280, 720));

        backToMenuButton.setText("Menu");
        backToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuButtonActionPerformed(evt);
            }
        });

        titleLayout.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleLayout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLayout.setText("Tutorial");

        stepLayout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        stepLayout.setText("1.Step: Choose your constructor and pick a nickname:");

        informationLayout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        informationLayout.setText("<html>First, you can choose from 3 team which define the difficulity.<br/>Next you need to type your nickname. </html>");
        informationLayout.setToolTipText("");

        pageNextButton.setText("Next");
        pageNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pageNextButtonActionPerformed(evt);
            }
        });

        pageBackButton.setText("Back");
        pageBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pageBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backToMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(stepLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addComponent(informationLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(picturesLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pageBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(pageNextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(519, 519, 519))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(informationLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stepLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(picturesLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pageNextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pageBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(backToMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuButtonActionPerformed
        try {
            window.switchToMenu(this);
        } catch (IOException ex) {
            Logger.getLogger(Tutorial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_backToMenuButtonActionPerformed

    private void pageNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pageNextButtonActionPerformed
        stepsNext();
    }//GEN-LAST:event_pageNextButtonActionPerformed

    private void pageBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pageBackButtonActionPerformed
        stepsPrevious();
    }//GEN-LAST:event_pageBackButtonActionPerformed

    public void stepsNext()
    {
        counter++;
        if(counter == 0)
        {
            picturesLayout.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/tutorial_1.png"));
            pageBackButton.setVisible(false);
            pageNextButton.setVisible(true);
            stepLayout.setText("1.Step: Choose your constructor and pick a nickname:");
            informationLayout.setText("<html>First, you can choose from 3 team which define the difficulity.<br/>Next you need to type your nickname. </html>");
        }
        else if(counter == 1)
        {
            picturesLayout.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/tutorial_2.png"));
            pageBackButton.setVisible(true);
            pageNextButton.setVisible(true);
            stepLayout.setText("2.Step: Departments,facilities investment, preppare for racing:");
            informationLayout.setText("<html>From the R&D panel, you can choose what you want to build.<br/> Races start after 3 days automaticly, but you can skipp the time by pressing the RaceWeek button.</html>");
        }
        else if(counter == 2)
        {
            picturesLayout.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/tutorial_3.png"));
            pageBackButton.setVisible(true);
            pageNextButton.setVisible(false);
            stepLayout.setText("3.Step: Interview, development points, race simulation:");
            informationLayout.setText("<html>First you need to answers some questions.<br/> Next, you can  assign your available points on the Dashboard.<br/> Lets start racing by pressing the Simulation button.</html>");
        }
    }
        public void stepsPrevious()
    {
        counter--;
        if(counter == 0)
        {
            picturesLayout.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/tutorial_1.png"));
            pageBackButton.setVisible(false);
            pageNextButton.setVisible(true);
            stepLayout.setText("1.Step: Choose your constructor and pick a nickname:");
            informationLayout.setText("<html>First, you can choose from 3 team which define the difficulity.<br/>Next you need to type your nickname. </html>");
        }
        else if(counter == 1)
        {
            picturesLayout.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/tutorial_2.png"));
            pageBackButton.setVisible(true);
            pageNextButton.setVisible(true);
            stepLayout.setText("2.Step: Departments,facilities investment, preppare for racing:");
            informationLayout.setText("<html>From the R&D panel, you can choose what you want to build.<br/> Races start after 3 days automaticly, but you can skipp the time by pressing the RaceWeek button.</html>");
        }
        else if(counter == 2)
        {
            picturesLayout.setIcon(new ImageIcon(Paths.get("").toAbsolutePath().toString() + "/src/main/java/Images/tutorial_3.png"));
            pageBackButton.setVisible(true);
            pageNextButton.setVisible(false);
            stepLayout.setText("3.Step: Interview, development points, race simulation:");
            informationLayout.setText("<html>First you need to answers some questions.<br/> Next, you can  assign your available points on the Dashboard.<br/> Lets start racing by pressing the Simulation button.</html>");

        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMenuButton;
    private javax.swing.JLabel informationLayout;
    private javax.swing.JButton pageBackButton;
    private javax.swing.JButton pageNextButton;
    private javax.swing.JLabel picturesLayout;
    private javax.swing.JLabel stepLayout;
    private javax.swing.JLabel titleLayout;
    // End of variables declaration//GEN-END:variables
}
